import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "primeflex/primeflex.css";
import "primeicons/primeicons.css";
import { PrimeReactProvider } from "primereact/api";
import "primereact/resources/primereact.css";
import "primereact/resources/themes/tailwind-light/theme.css";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + " h-screen"}>
        <PrimeReactProvider
          value={{ cssTransition: false }}
        >
          {children}
        </PrimeReactProvider>
      </body>
    </html>
  );
}
